default = {
    "Author"        : "Doc656",
    #Setting
    "hkanno64path"  : ".",
    #Gui
    "Load"          : "Load",
    "Speed"         : "Speed:",
    "Execute"       : "Execute",
    "changeDir"     : "hkanno64 path",
    #string
    "Select Folder" : "Select Folder",
    "Message"       : "Message",
    "Ask Update"    : "Update .hkx files?",
    "Ask Delete"    : "delete .txt files generated by hkanno64?",
    "Notification"  : "Animation files are modified!",
    #Warn
    "Warning"       : "Warning",
    "No hkanno64"   : "hkanno64.exe is not exist at the destinated path!",
    "No rootpath"   : "Root path is not selected!",
    "Unexpected"    : "Unexpected Error!",
}