# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        myfont = "font: 10pt \"Palatino Linotype\";"
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        MainWindow.setMinimumSize(QtCore.QSize(400, 300))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.load_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.load_btn.setStyleSheet(myfont)
        self.load_btn.setObjectName("load_btn")
        self.verticalLayout.addWidget(self.load_btn)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setStyleSheet(myfont)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.speed_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.speed_line.setStyleSheet(myfont)
        self.speed_line.setObjectName("speed_line")
        self.verticalLayout.addWidget(self.speed_line)
        self.execute_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.execute_btn.setStyleSheet(myfont)
        self.execute_btn.setObjectName("execute_btn")
        self.verticalLayout.addWidget(self.execute_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.changeDir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.changeDir.setStyleSheet(myfont)
        self.changeDir.setObjectName("changeDir")
        self.verticalLayout.addWidget(self.changeDir)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.treeView = QtWidgets.QTreeView(parent=self.centralwidget)
        self.treeView.setStyleSheet(myfont)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout.addWidget(self.treeView)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

